s1=list(input("enter list"))
s2=list(input("enter list2 "))
print(s1*2)
print(s1[0])
print(s1[0:2])
print(s1.count("1"))
print(s1.append(1))
print(s1.pop())
print(s1.extend(s2))
print(s1.sort())
print(s1.insert(1,1))
