s1=set(input("enter set value"))
s2=set(input("eneter set 2"))
print(s1-s2)
print(s1.union(s2))
print(s1&s2)
print(s1|s2)
print(s1&s2)
print(s1==s2)
print(s1>s2)
print(s1.pop())
print(list(s1))
print(tuple(s1))
help(set)
