t1=tuple(input("enter value "))
print(t1[0])
print(t1[1:3])
print(t1[::-1])
print(max(t1))
print(min(t1))
print(t1[-2])
print(t1+tuple("asd"))
print(type(t1))
print(t1.count(0))
print(t1.index(1))
print(t1*2)
